### ISSUE TITLE
expose board state 

### ISSUE THREAD

**Issue by lino-levan** [raydog/deno-chess#9]
It would be really nice for users to be able to query the board state. Perhaps something like `game.getPiece(x,y)`?

I will open a PR.

**Comment by raydog** [comment]
Hey @lino-levan! Sorry for the slow reply - I need to double-check my notification rules...

I added a `.getSpace(coord)` method in #11 that should let you query the board state directly. It doesn't take 2 numeric parameters like you were asking, but instead the space's coordinates in standard algebraic form (eg: "b2") since that's a wee bit more consistent with the other APIs. Hope this helps!
